#!/usr/bin/env node
/**
 * Embeds carousel config from .env into a JS module for Adobe I/O Runtime.
 * OpenWhisk web actions (raw-http) may not receive empty deploy-time inputs;
 * this build-time fallback ensures dataEndpoint/baseURL are always in the bundle.
 */

require('dotenv').config()

const fs = require('fs')
const path = require('path')

const outPath = path.join(__dirname, '../actions/mcp-server/action-config.js')

const config = {
    baseURL: (process.env.BASE_URL || process.env.baseURL || '').trim(),
    dataEndpoint: (process.env.DATA_ENDPOINT || process.env.dataEndpoint || '').trim(),
    RESOURCE_DOMAINS: (process.env.RESOURCE_DOMAINS || '').trim()
}

if (!config.dataEndpoint) {
    console.warn(
        'Warning: dataEndpoint is not set in .env. The carousel tool will fail until you set DATA_ENDPOINT or dataEndpoint.'
    )
}

const output = `/*
 * Auto-generated by scripts/embed-config.js — do not edit.
 * Carousel config inlined for Adobe I/O Runtime when action inputs are missing.
 */
module.exports = ${JSON.stringify(config, null, 2)}
`

fs.writeFileSync(outPath, output)
console.log(`Wrote ${outPath}`)
if (config.dataEndpoint) {
    console.log(`dataEndpoint: ${config.dataEndpoint}`)
}
