#!/usr/bin/env node
/**
 * Embeds built MCP App HTML into a JS module for Adobe I/O Runtime deployment.
 * Serverless actions only ship the webpack bundle — static/ is not deployed alongside it.
 */

const fs = require('fs')
const path = require('path')

const staticDir = path.join(__dirname, '../actions/mcp-server/static')
const outPath = path.join(__dirname, '../actions/mcp-server/embedded-ui.js')

const files = {
    productListHtml: 'product-list.html',
    productDetailHtml: 'product-detail.html',
    cartHtml: 'cart.html'
}

const embedded = {}
for (const [key, filename] of Object.entries(files)) {
    const filePath = path.join(staticDir, filename)
    if (!fs.existsSync(filePath)) {
        console.error(`Missing ${filePath}. Run "npm run build:ui" first.`)
        process.exit(1)
    }
    embedded[key] = fs.readFileSync(filePath, 'utf8')
    console.log(`Embedded ${filename} (${(embedded[key].length / 1024).toFixed(1)} KB)`)
}

const output = `/*
 * Auto-generated by scripts/embed-ui.js — do not edit.
 * MCP App HTML inlined for Adobe I/O Runtime (serverless bundle has no static/ folder).
 */
module.exports = ${JSON.stringify(embedded, null, 2)}
`

fs.writeFileSync(outPath, output)
console.log(`Wrote ${outPath}`)
